name: CI - Docker Hub

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  pipeline:
    uses: ./.github/workflows/build.yml
    with:
      runner: ubuntu-latest
      image: ${{ vars.DOCKERHUB_USERNAME }}/simple-java-maven-app
      registry: dockerhub
    secrets: inherit